# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.FileField(default=None, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
