# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 11:02
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('blog', '0003_posts_date_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Введите ключевые слова или словосочетания, разделенные запятой', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Ключевые слова'),
        ),
    ]
