# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 12:58
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_posts_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
    ]
