# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
