# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20171025_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img4',
        ),
    ]
