# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20171101_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsincart',
            name='price_per_item',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemsincart',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
