# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20171104_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsincart',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='itemsincart',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Category', verbose_name='Категория'),
        ),
    ]
