# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20171104_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsincart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
