# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 20:16
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Варианты разделения слова - фуарлг', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Ключевые слова'),
        ),
    ]
