# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 14:16
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20171105_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Введите ключевые слова или словосочетания в нижнем регистре, разделенные запятой', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Ключевые слова'),
        ),
    ]
