# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Заказ обратной связи', 'verbose_name_plural': 'Заказы обратной связи'},
        ),
    ]
